[[CXSparse]]
arch = "aarch64"
git-tree-sha1 = "196086b5a8bec9ad5d823e54f28e47ced6221f8d"
os = "macos"

    [[CXSparse.download]]
    sha256 = "9d3ea1abd68b5ff488a5f205adaa2ca78aa3d7fdac5fecc668ef4c1300d43391"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.aarch64-apple-darwin.tar.gz"
[[CXSparse]]
arch = "aarch64"
git-tree-sha1 = "e255e3e5381196aa59ff7cebab306acac85ef410"
libc = "glibc"
os = "linux"

    [[CXSparse.download]]
    sha256 = "4486360f39833bf72b9018df6d98c933274fa24827fedcdd2c1aef6ac4ca84e5"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.aarch64-linux-gnu.tar.gz"
[[CXSparse]]
arch = "aarch64"
git-tree-sha1 = "327183673e7a61f58dc809778a24bed4a987aa52"
libc = "musl"
os = "linux"

    [[CXSparse.download]]
    sha256 = "541a6ea8fc79e5b72349289ed5fd84781c205b975accd3372727d4af60d03076"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.aarch64-linux-musl.tar.gz"
[[CXSparse]]
arch = "aarch64"
git-tree-sha1 = "b0a3986aa528b5778701324383bd00f9ca00336e"
os = "freebsd"

    [[CXSparse.download]]
    sha256 = "0dbd077b2f4122bdf78250bc894911b576b170f35066a8526b88e713627278f3"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.aarch64-unknown-freebsd.tar.gz"
[[CXSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2c47db01af92f26883ec3365f97536e20bfd6330"
libc = "glibc"
os = "linux"

    [[CXSparse.download]]
    sha256 = "37ca390c66aeede6ec8b944956a19754a5e1b38ac9a41fd40debed4dffb780bc"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.armv6l-linux-gnueabihf.tar.gz"
[[CXSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "42b9f42aeaf59d8d22d16fb5c95ef6d5038ccbd3"
libc = "musl"
os = "linux"

    [[CXSparse.download]]
    sha256 = "53781ca3933f5f91b35776dffa1e8490e0c82cdd59be57256af9215715edcd98"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.armv6l-linux-musleabihf.tar.gz"
[[CXSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ca13031668a792bd8e4b6554afe0b1016ff9414f"
libc = "glibc"
os = "linux"

    [[CXSparse.download]]
    sha256 = "218570e818b07334b4e7ec241b37555f72cee18930df340088cb04be95b0f23a"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.armv7l-linux-gnueabihf.tar.gz"
[[CXSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eb8f679b454245c91caa10e5bed30fb2e8094b43"
libc = "musl"
os = "linux"

    [[CXSparse.download]]
    sha256 = "05d28f72ee83f59583a1977944b9d24d25be3bc3ab1995e501c5b32ff69a3768"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.armv7l-linux-musleabihf.tar.gz"
[[CXSparse]]
arch = "i686"
git-tree-sha1 = "29a32e6d3b2ebe9079882bb3cb2e0c191b4bcf21"
libc = "glibc"
os = "linux"

    [[CXSparse.download]]
    sha256 = "784ab10d54a5c33cd69bf43722675b22cab4a85b1f48fc3ac912118d519b98be"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.i686-linux-gnu.tar.gz"
[[CXSparse]]
arch = "i686"
git-tree-sha1 = "ef0647335574ec61817e06915e4de6557d95ba85"
libc = "musl"
os = "linux"

    [[CXSparse.download]]
    sha256 = "20ffc883e90dd861393932c5e62cebe67569d006b615d7dd579a610b941ba822"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.i686-linux-musl.tar.gz"
[[CXSparse]]
arch = "i686"
git-tree-sha1 = "01a5d794fa1f1d1bc68027b29b6937c1723ad20e"
os = "windows"

    [[CXSparse.download]]
    sha256 = "7ee8dfd106bfef99d91bb183c3a221f30f9aa07e4be66856363426ad55a2b8c9"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.i686-w64-mingw32.tar.gz"
[[CXSparse]]
arch = "powerpc64le"
git-tree-sha1 = "f14545e99bb3332545adde20cb2a6abdbeb86b46"
libc = "glibc"
os = "linux"

    [[CXSparse.download]]
    sha256 = "9ff947fd17b9cdf3931a2edc7e302258a45a2019f04253944e51cac225a5a314"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.powerpc64le-linux-gnu.tar.gz"
[[CXSparse]]
arch = "x86_64"
git-tree-sha1 = "e724c11471910fb52d5e2792aacb8f2af998f637"
os = "macos"

    [[CXSparse.download]]
    sha256 = "280a54553d4a006af1e2130338cb00f90ba685c805963f1bfb55418fb61d3a74"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.x86_64-apple-darwin.tar.gz"
[[CXSparse]]
arch = "x86_64"
git-tree-sha1 = "09e61d941c818b24c1c1c33568f80474801a5952"
libc = "glibc"
os = "linux"

    [[CXSparse.download]]
    sha256 = "060fe03b76700dac8d2b2228ca40420fc387952dd49c85a5b45e5f2f0c9d2472"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.x86_64-linux-gnu.tar.gz"
[[CXSparse]]
arch = "x86_64"
git-tree-sha1 = "157b32195cc5974e4d338b5a9569a918fe7e91c1"
libc = "musl"
os = "linux"

    [[CXSparse.download]]
    sha256 = "e745546d873d703778444450d568f3496ae5b0373e719c907dd9dd6828ee08bd"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.x86_64-linux-musl.tar.gz"
[[CXSparse]]
arch = "x86_64"
git-tree-sha1 = "47b9f31f195e026d4b5342f707e923b93001966a"
os = "freebsd"

    [[CXSparse.download]]
    sha256 = "fe6d26f53197a1c763c534c1112c4a26afa7145e71d8cece949d45183a66d565"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.x86_64-unknown-freebsd.tar.gz"
[[CXSparse]]
arch = "x86_64"
git-tree-sha1 = "21c76215fd9c8d5b7a2f97345cf56d1a7306ec82"
os = "windows"

    [[CXSparse.download]]
    sha256 = "1fe59f1f762eedb7a732dcd490bdc7b0033c255b085393953b826c482970da4f"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.x86_64-w64-mingw32.tar.gz"
