[[CXSparse]]
arch = "aarch64"
git-tree-sha1 = "e376f222960f095227543a53481e90db1cb45cba"
os = "macos"

    [[CXSparse.download]]
    sha256 = "0f9e50f4db4ad937b254e706f86428e1ecfc111b2ab125bb71b4b6976fce828f"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.aarch64-apple-darwin.tar.gz"
[[CXSparse]]
arch = "aarch64"
git-tree-sha1 = "d84c8d271466350b6cc1b57f84638719666db40f"
libc = "glibc"
os = "linux"

    [[CXSparse.download]]
    sha256 = "6022c8a2f9e00ffc0e4334c6c94257b4139fc316064388a912dacfe6ca540dda"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.aarch64-linux-gnu.tar.gz"
[[CXSparse]]
arch = "aarch64"
git-tree-sha1 = "d7a75922f01ad189cbebd4cd3298e71bbebf3955"
libc = "musl"
os = "linux"

    [[CXSparse.download]]
    sha256 = "d08cbe2a3dd1461459834a7d126e0f1d05643cc0e5ce6b13ed2f2d13e0551b68"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.aarch64-linux-musl.tar.gz"
[[CXSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1f37625270d165efa32ad27d52569eb2a7eaee4a"
libc = "glibc"
os = "linux"

    [[CXSparse.download]]
    sha256 = "0f2ee5cd8b3edf34b799ec5f598c1fc7ab449ae8f2772c4a54908c52765895b4"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.armv6l-linux-gnueabihf.tar.gz"
[[CXSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1a0393024d8109eb53a4fb363d135cebdbc6cb46"
libc = "musl"
os = "linux"

    [[CXSparse.download]]
    sha256 = "9b3ce97270d3a9a43598acde1a07fa9d70f6b21eeac3bb2a69b8132881f5ddc9"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.armv6l-linux-musleabihf.tar.gz"
[[CXSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "50abafbf04cab4b4670ece904f30f7ebc1ad7219"
libc = "glibc"
os = "linux"

    [[CXSparse.download]]
    sha256 = "6f0a28400da4c54e5faddc2bb1161c79105afd341339a501186c3fbb8b7fefdc"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.armv7l-linux-gnueabihf.tar.gz"
[[CXSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1487e22889f3b7623c679a5909968261a5eae2b8"
libc = "musl"
os = "linux"

    [[CXSparse.download]]
    sha256 = "ffd5dc6b871720435bc9bb186e443b5692622c218696a0becb39e87765915824"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.armv7l-linux-musleabihf.tar.gz"
[[CXSparse]]
arch = "i686"
git-tree-sha1 = "6bc2187790170a18a6744210b50ced1d47e670ab"
libc = "glibc"
os = "linux"

    [[CXSparse.download]]
    sha256 = "d6f021690dfc48e777857ccc94e9b6dd51d922dee01f806f1e02c9d3dc62bc37"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.i686-linux-gnu.tar.gz"
[[CXSparse]]
arch = "i686"
git-tree-sha1 = "0d5593cfb3f9ebb2f9ba3886216036cced78a355"
libc = "musl"
os = "linux"

    [[CXSparse.download]]
    sha256 = "13fef5a55f8f2cff1d5548663d880b7c0a98de09257791cbfd932a7e4ea5c630"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.i686-linux-musl.tar.gz"
[[CXSparse]]
arch = "i686"
git-tree-sha1 = "94aaad2f26afe8d3d11ec2bfd22596870ad2b943"
os = "windows"

    [[CXSparse.download]]
    sha256 = "2cb46fa7f822e0441f57642a14f71cfc958a534edcd077f1555f93ba05a7e12c"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.i686-w64-mingw32.tar.gz"
[[CXSparse]]
arch = "powerpc64le"
git-tree-sha1 = "e75bbe02a129f4ff4e64b873b4050fe2f749b118"
libc = "glibc"
os = "linux"

    [[CXSparse.download]]
    sha256 = "270ae733266b419d41de98152c5ab7eeda6872a85e63f9733dcf0677e7762361"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.powerpc64le-linux-gnu.tar.gz"
[[CXSparse]]
arch = "x86_64"
git-tree-sha1 = "5164bcd1a09aa9415329d3bac06c17acbe79412f"
os = "macos"

    [[CXSparse.download]]
    sha256 = "43ea9e1a63a456229882c39a614bb449f9ff03e1a36a9ff66453adb4467f6b1d"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.x86_64-apple-darwin.tar.gz"
[[CXSparse]]
arch = "x86_64"
git-tree-sha1 = "d983e9be857c0ae325edd81a10d3c700929525fd"
libc = "glibc"
os = "linux"

    [[CXSparse.download]]
    sha256 = "67dec0d5bcda508dfa61fa5875779a3130966fdf65df0938c64d78fdb6ac3881"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.x86_64-linux-gnu.tar.gz"
[[CXSparse]]
arch = "x86_64"
git-tree-sha1 = "01d3b1450409d2f14d322dd0418ce86ccb5c2359"
libc = "musl"
os = "linux"

    [[CXSparse.download]]
    sha256 = "b06d59b0c2e015ca83c22ed41ed5d3cb9f845e3ce8709073856b73b9bc507887"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.x86_64-linux-musl.tar.gz"
[[CXSparse]]
arch = "x86_64"
git-tree-sha1 = "57c9955e755dd81908333fff6d842331ab81e29a"
os = "freebsd"

    [[CXSparse.download]]
    sha256 = "730536e88c90a464e3aac294642a02e7a47b6a1de35558f500057d1b809231bc"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.x86_64-unknown-freebsd.tar.gz"
[[CXSparse]]
arch = "x86_64"
git-tree-sha1 = "345812569fb052b5006383aff1071d8021bba22a"
os = "windows"

    [[CXSparse.download]]
    sha256 = "4adc8e3037874d7a113f914d50fa365c0662b1637a9ec713b317b4e5db3484d4"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v4.4.0+0/CXSparse.v4.4.0.x86_64-w64-mingw32.tar.gz"
