[[CXSparse]]
arch = "aarch64"
git-tree-sha1 = "e668202d61e801ffff0aa6c50962367bc9b1ab5a"
os = "macos"

    [[CXSparse.download]]
    sha256 = "923cc302040c57bc93de96073a33e85e28fa35314f580ca867af61769738639e"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v5.10.1+1/CXSparse.v5.10.1.aarch64-apple-darwin.tar.gz"
[[CXSparse]]
arch = "aarch64"
git-tree-sha1 = "2f87eb2e49faa9fbdfa27064e6de4eca8d78a904"
libc = "glibc"
os = "linux"

    [[CXSparse.download]]
    sha256 = "83ac138b677500c83989ac75105f6d62220f2c12bbbba0f844519b7d63b4f2b2"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v5.10.1+1/CXSparse.v5.10.1.aarch64-linux-gnu.tar.gz"
[[CXSparse]]
arch = "aarch64"
git-tree-sha1 = "bf4e70677d4f00d6299c5f465ec1638b33efe129"
libc = "musl"
os = "linux"

    [[CXSparse.download]]
    sha256 = "786221d6c9e107a7184eb7f30efa4e6df1f3a4e09abe45fdbdb9acfb3cff4605"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v5.10.1+1/CXSparse.v5.10.1.aarch64-linux-musl.tar.gz"
[[CXSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "249856e5ba080e14af5e14e93a169e351f3cc6ee"
libc = "glibc"
os = "linux"

    [[CXSparse.download]]
    sha256 = "baf2672b24268a4fb70206005bfdbb13c3da092e47b2a67f9138e34020c758be"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v5.10.1+1/CXSparse.v5.10.1.armv6l-linux-gnueabihf.tar.gz"
[[CXSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6aaa4ddd246e723c1f120f19d565b7f8f26fbc6f"
libc = "musl"
os = "linux"

    [[CXSparse.download]]
    sha256 = "f69b591058d2e45948fc8aa7f43c9855c52b15cd6e5563fb2300c2d46634be8e"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v5.10.1+1/CXSparse.v5.10.1.armv6l-linux-musleabihf.tar.gz"
[[CXSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4ce8b2aca8394baefd2acacb61a526b4a06f59c4"
libc = "glibc"
os = "linux"

    [[CXSparse.download]]
    sha256 = "db137115aa8cd58959c1c400e87f9f9fa33032348486af51daf31db8ff32c9ff"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v5.10.1+1/CXSparse.v5.10.1.armv7l-linux-gnueabihf.tar.gz"
[[CXSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "99b20772590192b3cc2635a829fbd5b30da070af"
libc = "musl"
os = "linux"

    [[CXSparse.download]]
    sha256 = "4b45d93bb136e7eea6545b5b433dde744f5ad2ac87780d2645dabf7bfad89249"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v5.10.1+1/CXSparse.v5.10.1.armv7l-linux-musleabihf.tar.gz"
[[CXSparse]]
arch = "i686"
git-tree-sha1 = "667dbb95d4a2fd107409d551a778f8f1b0ccfca7"
libc = "glibc"
os = "linux"

    [[CXSparse.download]]
    sha256 = "e71408be65439fb7692ca35e5517504a19c5493606c278173dca75ec6638f87e"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v5.10.1+1/CXSparse.v5.10.1.i686-linux-gnu.tar.gz"
[[CXSparse]]
arch = "i686"
git-tree-sha1 = "dc301ea6c7bd1dceb8bc3503f5726175b62006d0"
libc = "musl"
os = "linux"

    [[CXSparse.download]]
    sha256 = "d488b0a8f955e9b0ac8383b2007e1940b1d930ba3089ad10e7412aab485707d3"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v5.10.1+1/CXSparse.v5.10.1.i686-linux-musl.tar.gz"
[[CXSparse]]
arch = "i686"
git-tree-sha1 = "b6170699fba1852e73d372687acdc30fc6182f0d"
os = "windows"

    [[CXSparse.download]]
    sha256 = "88d33b4f95ccaecbfe1e10185cef38c1d368158fa1caa9d203a499e9fbc7ade8"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v5.10.1+1/CXSparse.v5.10.1.i686-w64-mingw32.tar.gz"
[[CXSparse]]
arch = "powerpc64le"
git-tree-sha1 = "25e36f966fc164c1d791fda0d68f05c3f48b2e6a"
libc = "glibc"
os = "linux"

    [[CXSparse.download]]
    sha256 = "202847f48fdbfcaad9e7942de205e8bc4b9d59a69113c111e3f55a42284abac9"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v5.10.1+1/CXSparse.v5.10.1.powerpc64le-linux-gnu.tar.gz"
[[CXSparse]]
arch = "x86_64"
git-tree-sha1 = "84e307109228904ff0d1615ad03d23a5bc43030a"
os = "macos"

    [[CXSparse.download]]
    sha256 = "8c8d4e3b4f3deef5a86dfeec4fa2fca1079ae5c214b25c3ed75f93043439d3d0"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v5.10.1+1/CXSparse.v5.10.1.x86_64-apple-darwin.tar.gz"
[[CXSparse]]
arch = "x86_64"
git-tree-sha1 = "d1fdccb74c17f8664238b38086b180a2f0824da7"
libc = "glibc"
os = "linux"

    [[CXSparse.download]]
    sha256 = "343fc211fb7e9f441f6c9d3f823733fde1e50bdfbd71fcd09bba17ba002e8683"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v5.10.1+1/CXSparse.v5.10.1.x86_64-linux-gnu.tar.gz"
[[CXSparse]]
arch = "x86_64"
git-tree-sha1 = "eb685d9f9a37cde89aeb7101844e876fee1cbafc"
libc = "musl"
os = "linux"

    [[CXSparse.download]]
    sha256 = "5024534aae8708ad22aeeb6a523c617aea5cd4332c8d33136fb0f392518a39b6"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v5.10.1+1/CXSparse.v5.10.1.x86_64-linux-musl.tar.gz"
[[CXSparse]]
arch = "x86_64"
git-tree-sha1 = "a70b2a79615144ffd22c62917320f1008fcc8dee"
os = "freebsd"

    [[CXSparse.download]]
    sha256 = "857d07a21540a638ed1bdd14bf5a677a02b7d2db1efa09a24005070526c2d75e"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v5.10.1+1/CXSparse.v5.10.1.x86_64-unknown-freebsd.tar.gz"
[[CXSparse]]
arch = "x86_64"
git-tree-sha1 = "df0ea9cd85ed0f35de04974f39ef5b078cb15b55"
os = "windows"

    [[CXSparse.download]]
    sha256 = "73879a8d16742c6400018dbf5a38949e9e6763aea7a80b9fc1e97ee8cf000ca5"
    url = "https://github.com/JuliaBinaryWrappers/CXSparse_jll.jl/releases/download/CXSparse-v5.10.1+1/CXSparse.v5.10.1.x86_64-w64-mingw32.tar.gz"
