# Autogenerated wrapper script for CXSparse_jll for x86_64-apple-darwin
export libcxsparse

using SuiteSparse_jll
JLLWrappers.@generate_wrapper_header("CXSparse")
JLLWrappers.@declare_library_product(libcxsparse, "@rpath/libcxsparse.3.dylib")
function __init__()
    JLLWrappers.@generate_init_header(SuiteSparse_jll)
    JLLWrappers.@init_library_product(
        libcxsparse,
        "lib/libcxsparse.3.2.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
