# Autogenerated wrapper script for CXSparse_jll for x86_64-w64-mingw32
export libcxsparse, libsuitesparseconfig_cxsparse

using libblastrampoline_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("CXSparse")
JLLWrappers.@declare_library_product(libcxsparse, "libcxsparse.dll")
JLLWrappers.@declare_library_product(libsuitesparseconfig_cxsparse, "libsuitesparseconfig.dll")
function __init__()
    JLLWrappers.@generate_init_header(libblastrampoline_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libcxsparse,
        "bin\\libcxsparse.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsuitesparseconfig_cxsparse,
        "bin\\libsuitesparseconfig.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
